# Generated by Django 6.0.5 on 2026-05-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_remove_student_lecture_student_lecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="lecture",
        ),
        migrations.CreateModel(
            name="LectureStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturestudent",
                        to="lectures.lecture",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturestudent",
                        to="lectures.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="lecture",
            field=models.ManyToManyField(
                related_name="students",
                through="lectures.LectureStudent",
                to="lectures.lecture",
            ),
        ),
    ]
